[build]
  command = "npm run build"
  publish = ".next"  # Correct directory for Next.js build output
  functions = "netlify/functions"  # If you have custom functions, set the path here

[[plugins]]
  package = "@netlify/plugin-nextjs"
